### PR TITLE
Bump version to 1.4.3

### PR DESCRIPTION
**Pull request by jarib**
I needed 1.4.3 since I wanted to try the latest Kibana beta, which
requires it. So I did this :)

### CODE REVIEW

**Comment by tarebyte** [comment]
Would you mind updating the specs as well? Thanks!

**Comment by jarib** [comment]
Done. `script/cibuild` is now passing on my Mac, but still failing on Travis for no obvious reason.

**Comment by tarebyte** [comment]
@jarib I'll check it out later tonight

**Comment by jarib** [comment]
Replaced by #22

**Pull request closed without merging**
